{
  "openapi": "3.0.2",
  "info": {
    "title": "Perpustakaan API",
    "version": "1.0",
    "description": "Tugas Swagger"
  },

  "servers": [{ "url": "http://localhost:3000/" }],
  "paths": {
    "/user": {
      "get": {
        "description": "(Daftar anggota perpustakaan) Mengambil semua data anggota perpustakaan atau user",
        "tags": ["User"],
        "parameters": [],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "id": {
                            "type": "integer"
                          },
                          "nama": {
                            "type": "string"
                          }
                        }
                      },
                      "example": [
                        {
                          "id": 1,
                          "nama": "ridho"
                        },
                        {
                          "id": 2,
                          "nama_": "aris"
                        }
                      ]
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "msg": {
                      "type": "string",
                      "example": "Not Found Buku"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Error server",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "msg": {
                      "type": "string",
                      "example": "Error message"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/user/{user}": {
      "get": {
        "description": "(Riwayat peminjaman) Mengambil data riwayat pinjaman",
        "tags": ["User"],
        "parameters": [
          {
            "name": "user",
            "description": "masukkan nama user",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "field status mempresentasikan 0/false belom di kembalikan dan 1/true sudah di kembalikan",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "id": {
                            "type": "integer"
                          },
                          "nama": {
                            "type": "string"
                          }
                        }
                      },
                      "example": [
                        {
                          "userId": 1,
                          "bukuId": 1,
                          "status": 0
                        },
                        {
                          "userId": 1,
                          "bukuId": 2,
                          "status": 1
                        }
                      ]
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found. User tidak pernah meminjam apapun",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "msg": {
                      "type": "string",
                      "example": "Not Found History"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Error server",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "msg": {
                      "type": "string",
                      "example": "Error message"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },

    "/buku": {
      "get": {
        "description": "(Daftar buku yang tersedia) Mengambil semua data buku yang tersedia atau ada dengan keadaan status false/0 sebagai tanda dalam keadaan tidak sedang di pinjam",
        "tags": ["Buku"],
        "parameters": [],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "id": {
                            "type": "integer"
                          },
                          "nama": {
                            "type": "string"
                          }
                        }
                      },
                      "example": [
                        {
                          "id": 1,
                          "nama_buku": "kelinci kecil",
                          "penerbit": "susilo",
                          "tanggal_release": "12-12-2011",
                          "status": 0,
                          "dipinjam": 10
                        },
                        {
                          "id": 2,
                          "nama_buku": "kelinci kecil",
                          "penerbit": "susilo",
                          "tanggal_release": "12-12-2011",
                          "status": 0,
                          "dipinjam": 1
                        }
                      ]
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "msg": {
                      "type": "string",
                      "example": "Not Found Buku"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Error server",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "msg": {
                      "type": "string",
                      "example": "Error message"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/buku/{keyword}": {
      "get": {
        "description": "(Pencarian buku) Mencari Buku berdasarkan keyword yang di inputkan sebagaimana buku dapat di cari berdasarkan nama_buku,penerbit, dan id",
        "tags": ["Buku"],
        "parameters": [
          {
            "name": "keyword",
            "in": "path",
            "description": "Masukkan nama buku atau penerbit buku ataupun id buku",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Example mencari buku dengan ",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "id": {
                            "type": "integer"
                          },
                          "nama": {
                            "type": "string"
                          }
                        }
                      },
                      "example": [
                        {
                          "id": 1,
                          "nama_buku": "kelinci kecil",
                          "penerbit": "susilo",
                          "tanggal_release": "12-12-2011",
                          "status": 0
                        },
                        {
                          "id": 2,
                          "nama_buku": "kelinci kecil",
                          "penerbit": "susilo",
                          "tanggal_release": "12-12-2011",
                          "status": 0
                        }
                      ]
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "msg": {
                      "type": "string",
                      "example": "Not Found Buku"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Error server",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "msg": {
                      "type": "string",
                      "example": "Error message"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/buku/{id}": {
      "get": {
        "description": "(Detail buku) Mengambil data buku tertentu dari id Buku",
        "tags": ["Buku"],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "object",
                      "example": {
                        "id": 1,
                        "nama_buku": "kelinci kecil",
                        "penerbit": "susilo",
                        "tanggal_release": "12-12-2011",
                        "status": 1
                      }
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "msg": {
                      "type": "string",
                      "example": "Buku id Not Found."
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Server error.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "msg": {
                      "type": "string",
                      "example": "Error"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "put": {
        "description": "(Peminjaman buku) Meminjam Buku berdasarkan id Buku dan nama yang pinjam buku",
        "tags": ["Buku"],
        "security": [{ "bearerAuth": [] }],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": ["nama"],
                "properties": {
                  "nama": {
                    "type": "string"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "msg": {
                      "type": "string",
                      "example": "success"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "msg": {
                      "type": "string",
                      "example": "Nama Not Found"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Server error.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "msg": {
                      "type": "string",
                      "example": "error"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "msg": {
                      "type": "string",
                      "example": "Please Login First"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "description": "(Pengembalian buku) Mengembalikan buku yang telah di pinjam oleh user berdasarkan kode buku / id buku, jika sudah selesai di pinjam maka akan mengganti status dari awalnya 1/true menjadi false/0 yang berarti sedang tidak di pinjam",
        "tags": ["Buku"],
        "security": [{ "bearerAuth": [] }],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "id": {
                            "type": "integer"
                          },
                          "nama": {
                            "type": "string"
                          },
                          "nama_buku": {
                            "type": "string"
                          },
                          "penerbit": {
                            "type": "string"
                          },
                          "tanggal_release": {
                            "type": "string"
                          },
                          "status": {
                            "type": "integer"
                          }
                        },
                        "example": [
                          {
                            "id": 1,
                            "nama_buku": "kelinci kecil",
                            "penerbit": "susilo",
                            "tanggal_release": "12-12-2011",
                            "status": 0
                          }
                        ]
                      }
                    },
                    "msg": {
                      "type": "string",
                      "example": "success"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Server error.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "msg": {
                      "type": "string",
                      "example": "error"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "msg": {
                      "type": "string",
                      "example": "do not have access rights"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "msg": {
                      "type": "string",
                      "example": "id Buku Not Found"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/rekomendasi": {
      "get": {
        "description": "(Rekomendasi buku) Mengambil data buku dengan jumlah peminjaman 10 atau ke atas",
        "tags": ["Buku"],
        "parameters": [],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "id": {
                            "type": "integer"
                          },
                          "nama": {
                            "type": "string"
                          }
                        }
                      },
                      "example": [
                        {
                          "id": 1,
                          "nama_buku": "kelinci kecil",
                          "penerbit": "susilo",
                          "tanggal_release": "12-12-2011",
                          "status": 0,
                          "dipinjam": 10
                        }
                      ]
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "msg": {
                      "type": "string",
                      "example": "Not Found Buku"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Error server",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "msg": {
                      "type": "string",
                      "example": "Error message"
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  }
}
